accounts/urls.py
from django.urls import path
from . import views
from .forms import ResetPasswordEmailValidation

app_name = 'accounts'
urlpatterns = [
    # authenticate
    path('register', views.RegisterView.as_view(), name='register_page'),
    path('register-verify', views.verify_register, name='verify_register'),
    path('resend-sms', views.resent_sms, name='resent_sms'),
    path('login', views.LoginView.as_view(), name='login_page'),
    path('logout', views.LogoutView.as_view(), name='logout_page'),

    # reset password phone
    path('forgot-password', views.forgot_password, name='forgot_password'),
    path('reset-password/<user_temp_code>', views.reset_password, name='reset_password'),

    # change password
    path('change-password', views.ChangePasswordView.as_view(), name='change_password'),

    # reset password email
    path('reset', views.ResetPasswordView.as_view(form_class=ResetPasswordEmailValidation),
         name='reset_password_email'),
    path('reset/done', views.ResetPasswordDoneView.as_view(), name='reset_password_done_email'),
    path('confirm/<uidb64>/<token>/', views.ResetPasswordConfirmView.as_view(), name='reset_password_confirm_email'),
    path('confirm/done', views.ResetPasswordCompleteView.as_view(), name='reset_password_complete_email'),

    # profile
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('orders', views.OrderListView.as_view(), name='order_list'),
    path('favourite', views.FavouriteListView.as_view(), name='favourite'),
    path('comments', views.CommentsListView.as_view(), name='comments'),
    path('comments/<commentId>', views.comment_delete, name='comment_delete'),
    path('profile-info', views.ProfileInfoView.as_view(), name='profile_info'),
    # path('order-detail', views.OrderDetailView.as_view(), name='order_detail'),

    # delete order by user
    path('order-delete/<orderId>', views.order_delete, name='order_delete'),
    path('order-update/<orderId>', views.order_update, name='order_update'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('mag', views.BlogHome.as_view(), name='blog_home'),
    path('mag/<article_slug>', views.blog_detail, name='blog_detail'),
    path('mag/category/<categorySlug>', views.BlogCategoryListView.as_view(), name='blog_category_list'),
    path('mag/tag/<tagSlug>', views.BlogTagListView.as_view(), name='blog_tag_list'),
    path('mag/search/', views.BlogSearchListView.as_view(), name='blog_search_list'),
    path('mag/add-commet/<articleId>', views.add_blog_comment, name='add_blog_comment'),
    path('mag/add-article-comment-reply/<int:articleId>/<int:commentId>', views.add_blog_comment_reply,
         name='add_blog_comment_reply'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from services.sitemaps import *

sitemaps = {
    'homes': HomesViewSitemap,
    'product': ProductViewSitemap,
    'article': ArticleViewSitemap,
}



urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('ticket.urls', namespace='ticket')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('compare.urls', namespace='compare')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.home, name='home_page'),
    path('product/<product_slug>', views.product_detail, name='product_detail_page'),
    path('comment/<productId>', views.product_comment, name='product_comment'),
    path('like_comment/<commentId>', views.comment_like, name='comment_like'),
    path('dislike_comment/<commentId>', views.comment_dislike, name='comment_dislike'),
    path('category/<category_slug>', views.category_list, name='category_list'),
    path('tag/<tag_slug>', views.tag_list, name='tag_list'),
    path('brand/<brand_slug>', views.brand_list, name='brand_list'),
    path('search/', views.SearchListView.as_view(), name='search'),
    # favourite products
    path('favourite/<productSlug>', views.favourite_product, name='favourite_product'),
]

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views import View
from .forms import RegisterForm, LoginForm, VerifyRegistrationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import UpdateView
from django.contrib import messages
from random import randint
from ippanel import Client
from core.settings import SMS_API_KEY
from .models import User
from .forms import ForgotPasswordForm, VerifyResetPassword, ChangePasswordForm
from django.utils.crypto import get_random_string
from django.contrib.auth.decorators import login_required
# email auth imports
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
# orders imports
from order.models import Order
from store.models import Comment

api_key = SMS_API_KEY
sms = Client(api_key)


class RegisterView(View):
    def get(self, request):
        register_form = RegisterForm()
        context = {
            'form': register_form
        }
        if request.user.is_authenticated:
            return redirect('store:home_page')
        return render(request, 'accounts/register_page.html', context)

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            data = register_form.cleaned_data
            user = User(first_name=data['first_name_form'],
                        last_name=data['last_name_form'],
                        email=data['email_form'], phone=data['phone_number_form'],
                        password=data['confirm_password_form'])
            user.set_password(data['confirm_password_form'])
            user.save()
            login(request, user)
            verify_code = randint(1111, 9999)
            request.session['verify_auth'] = verify_code
            pattern_values = {
                "code": f"{verify_code}",
            }
            sms.send_pattern(
                "your pattern code",
                f"your number",
                f"{user.phone}",
                pattern_values,
            )
            print(request.session['verify_auth'])
            messages.success(request,
                             f'ثبت نام شما با موفقیت انجام شد. لطفا برای فعالسازی کد تایید برای شماره {user.phone} را وارد کنید.')
            return redirect('accounts:verify_register')


def verify_register(request):
    if request.method == 'POST':
        form = VerifyRegistrationForm(request.POST)
        if form.is_valid():
            verify_code = form.cleaned_data['code']
            verify_session = request.session['verify_auth']
            if verify_code == verify_session:
                user = request.user
                if not user.is_verify:
                    user.is_verify = True
                    user.save()
                    del verify_session
                    messages.success(request, 'ثبت نام شما با موفقیت انجام شد.')
                    return render(request, 'accounts/register_done.html')
                else:
                    messages.info(request, 'شما کاربر تایید شده هستید.')
                    return redirect('accounts:verify_register')
            else:
                messages.warning(request, 'کد تایید صحیح نمیباشد.')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = VerifyRegistrationForm()
        return render(request, 'accounts/verify_code_auth.html', {'form': form})


def resent_sms(request):
    if not request.user.is_verify:
        verify_code = randint(1111, 9999)
        request.session['verify_auth'] = verify_code
        pattern_values = {
            "code": f"{request.session['verify_auth']}",
        }
        sms.send_pattern(
            "5drzq2t5yg5akmh",
            f"3000505",
            f"{request.user.phone}",
            pattern_values,
        )
        messages.success(request, f'کد فعالسازی دوباره برای {request.user.phone} ارسال شد.')
        return redirect('accounts:verify_register')
    else:
        messages.info(request, 'کاربر گرامی شما تایید شده اید. میتوانید از خدمات همتا گیم استفاده نمایید.')
        return redirect('accounts:verify_register')


def forgot_password(request):
    form = ForgotPasswordForm()
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            user_phone_number = form.cleaned_data['phone_number_form']
            user = User.objects.filter(phone__iexact=user_phone_number).first()
            if user is not None:
                reset_password_code = randint(111111, 999999)
                request.session['reset_password_session'] = reset_password_code
                user.temp_code = get_random_string(250)
                user.save()
                # send verify reset password sms here
                print(reset_password_code)
                messages.success(request, f'کد بازیابی رمز عبور برای شماره {user.phone} ارسال شد.')
                return redirect('accounts:reset_password', user.temp_code)
    return render(request, 'accounts/forgot_password_phone_page.html', {'form': form})


def reset_password(request, user_temp_code):
    the_user = User.objects.get(temp_code__iexact=user_temp_code)
    temp_code = the_user.temp_code
    form = VerifyResetPassword()
    if request.method == 'POST':
        form = VerifyResetPassword(request.POST)
        if form.is_valid():
            reset_password_code = form.cleaned_data['reset_password_code']
            confirm_reset_password_form = form.cleaned_data['confirm_reset_password_form']
            verify_reset_password = request.session['reset_password_session']
            if verify_reset_password == reset_password_code:
                the_user.set_password(confirm_reset_password_form)
                the_user.temp_code = None
                the_user.save()
                del request.session['reset_password_session']
                messages.success(request, f'رمز عبور شما تغییر یافت.')
                return redirect('accounts:login_page')
            else:
                messages.warning(request, 'کد تایید اشتباه است.')
                return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'accounts/reset_password_phone_page.html', {'form': form, 'temp_code': temp_code})


class ResetPasswordView(auth_views.PasswordResetView):
    template_name = 'accounts/reset_password_page.html'
    success_url = reverse_lazy('accounts:reset_password_done_email')
    email_template_name = 'accounts/link.html'


class ResetPasswordDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/reset_password_done_page.html'


class ResetPasswordConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/reset_password_confirm_page.html'
    success_url = reverse_lazy('accounts:reset_password_complete_email')


class ResetPasswordCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/reset_password_complete_page.html'


class LoginView(View):
    def get(self, request):
        login_form = LoginForm()
        context = {
            'login_form': login_form,
        }
        if request.user.is_authenticated:
            return redirect('store:home_page')
        return render(request, 'accounts/login_page.html', context)

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            data = login_form.cleaned_data
            user = authenticate(phone=data['phone_number_form'], password=data['password_form'])
            if user is not None:
                login(request, user)
                messages.success(request, 'با موفقیت به حساب خود وارد شدید.')
                return redirect('store:home_page')
        else:
            print('error')
        context = {
            'login_form': login_form,
        }
        return render(request, 'accounts/login_page.html', context)


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            messages.success(request, 'با موفقیت از حساب خود خارج شدید.')
            return redirect('accounts:login_page')


class DashboardView(View):
    def get(self, request):
        user = request.user
        if user.is_verify:
            context = {
                'user': user,
                'favorite_products': request.user.favourites_user.all(),
            }
            return render(request, 'accounts/profile/dashboard.html', context)
        messages.warning(request, 'کاربر گرامی لطفا شماره تلفن خود را تایید کنید.')
        return redirect('store:home_page')


class OrderListView(View):
    def get(self, request):
        user_id = request.user.id
        paid_orders = Order.objects.filter(user_id=user_id, status='P').order_by('-id')
        sending_orders = Order.objects.filter(user_id=user_id, status='S').order_by('-id')
        received_orders = Order.objects.filter(user_id=user_id, status='R').order_by('-id')
        canceled_orders = Order.objects.filter(user_id=user_id, is_paid=False).order_by('-id')
        context = {
            'paid_orders': paid_orders,
            'sending_orders': sending_orders,
            'received_orders': received_orders,
            'canceled_orders': canceled_orders,
        }
        if request.user.is_authenticated:
            return render(request, 'accounts/profile/profile_orders_page.html', context)
        return redirect('home:home_page')


class FavouriteListView(View):
    def get(self, request):
        if request.user.is_authenticated and request.user.is_verify:
            products = request.user.favourites_user.all()
            count = products.count()
            print(count)
            return render(request, 'accounts/profile/favourite.html', {'products': products})
        else:
            return redirect('accounts:login_page')

class CommentsListView(View):

accounts/templates/accounts/forgot_password_phone_page.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block window_title %}{% endblock %}</title>
    <!-- font-awesome -->
    <link rel="stylesheet" href="{% static '' %}css/font-awesome.min.css">
    <!-- Bootstrap 4.5.3 -->
    <link rel="stylesheet" href="{% static '' %}bootstrap/css/bootstrap.min.css">
    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{% static '' %}css/plugins/apexcharts.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/jquery.classycountdown.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/nouislider.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/sweetalert2.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/select2.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/swiper.min.css">
    <!-- CSS Template -->
    <link rel="stylesheet" href="{% static '' %}css/theme.css">
    <!-- Here goes your custom.css -->
    <link rel="stylesheet" href="{% static '' %}css/custom.css">
    <!-- colors: amber,blue,brown,cyan,default,green,indigo,orange,pink,purple,red,teal,yellow -->
    <link rel="stylesheet" href="{% static '' %}css/colors/default.css" id="colorswitch">
</head>

<body>

<main class="page-content">
    {% include 'messages.html' %}
    <div class="container">
        <div class="auth-wrapper">
            <div class="auth-form shadow-around">
                <div class="site-logo">
                    <a href="{% url 'store:home_page' %}">
                        <img src="{{ site_setting.site_header_logo.url }}"
                                 alt="{{ site_setting.site_header_logo_alt }}">
                    </a>
                </div>
                <div class="auth-form-title">
                    یادآوری کلمه عبور
                </div>

                <form action="{% url 'accounts:forgot_password' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <div class="form-element-row text-left mt-3">
                        <button type="submit" class="btn-element btn-success-element btn-block">
                            <i class="fad fa-sync"></i>
                            بازیابی رمز عبور
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
<!-- JS Global Compulsory -->
<script src="{% static '' %}js/jquery-3.5.1.min.js"></script>
<script src="{% static '' %}js/plugins/popper.min.js"></script>
<script src="{% static '' %}bootstrap/js/bootstrap.min.js"></script>
<!-- JS Implementing Plugins -->
<script src="{% static '' %}js/plugins/apexcharts.min.js"></script>
<script src="{% static '' %}js/plugins/jquery.knob.js"></script>
<script src="{% static '' %}js/plugins/jquery.throttle.js"></script>
<script src="{% static '' %}js/plugins/jquery.classycountdown.min.js"></script>
<script src="{% static '' %}js/plugins/jquery.nicescroll.min.js"></script>
<script src="{% static '' %}js/plugins/nouislider.min.js"></script>
<script src="{% static '' %}js/plugins/sweetalert2.all.min.js"></script>
<script src="{% static '' %}js/plugins/select2.full.min.js"></script>
<script src="{% static '' %}js/plugins/swiper.min.js"></script>
<script src="{% static '' %}js/plugins/ResizeSensor.min.js"></script>
<script src="{% static '' %}js/plugins/theia-sticky-sidebar.min.js"></script>
<script src="{% static '' %}js/plugins/zoomsl.min.js"></script>
<script src="{% static '' %}js/plugins/wNumb.js"></script>
<!-- JS Template -->
<script src="{% static '' %}js/theme.js"></script>
<!-- Here goes your custom.js -->
<script src="{% static '' %}js/custom.js"></script>

<script>
    $(document).ready(function () {
        $('#countdown--offer-slider').ClassyCountdown({
            theme: "black",
            end: $.now() + 645600,
            labels: false,
        });
    });
</script>
</body>

</html>

accounts/templates/accounts/link.html
لینک تغییر رمز عبور ارسال شد
{{ protocol }}://{{ domain }}{% url 'accounts:reset_password_confirm_email' uidb64=uid token=token %}

accounts/templates/accounts/login_page.html
{% extends 'base.html' %}
{% load static %}
{% block window_title %}{% endblock %}

{% block content %}
    <main class="page-content">
        <div class="container">
            <div class="auth-wrapper">
                <div class="auth-form shadow-around">
                    <div class="site-logo">
                        <a href="{% url 'store:home_page' %}">
                            <img src="{{ site_setting.site_header_logo.url }}"
                                 alt="{{ site_setting.site_header_logo_alt }}">
                        </a>
                    </div>
                    <div class="auth-form-title">
                        ورود به همتا
                    </div>
                    <form action="{% url 'accounts:login_page' %}" method="post">
                        {% csrf_token %}
                        {{ login_form }}
                        <div class="form-element-row text-left mt-3">
                            <button type="submit" class="btn-element btn-info-element btn-block">
                                <i class="fad fa-sign-in-alt"></i>
                                ورود به همتا گیم
                            </button>
                        </div>

                    </form>
                    <div class="auth-form-footer">
                        <span>کاربر جدید هستید؟</span>
                        <a href="{% url 'accounts:register_page' %}" class="link--with-border-bottom">ثبت نام در
                            همتا</a>
                        <br>
                        <a href="{% url 'accounts:forgot_password' %}" class="link--with-border-bottom">
                            بازیابی گذواژه با شماره همراه
                        </a>
                        <br>
                        <a href="{% url 'accounts:reset_password_email' %}" class="link--with-border-bottom">
                            بازیابی گذرواژه با ایمیل
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}
{% load static %}
{% block window_title %}{% endblock %}

{% block content %}
    <main class="page-content">
        <div class="container">
            <div class="auth-wrapper">
                <div class="auth-form shadow-around">
                    <div class="site-logo">
                        <a href="#">
                            <img src="{{ site_setting.site_header_logo }}"
                                 alt="{{ site_setting.site_header_logo_alt }}">
                        </a>
                    </div>
                    <div class="auth-form-title">
                        ثبت نام و تایید کد با موفقیت انجام شد. به همتا گیم خوش آمدید
                    </div>
                    <div class="auth-form-footer">
                        اکنون میتوانید به حساب کاربری خود
                        <a href="{% url 'accounts:login_page' %}" class="link--with-border-bottom">
                            وارد
                        </a>
                         شوید.
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/register_page.html
{% extends 'base.html' %}
{% load static %}
{% block window_title %}
    ثبت نام در همتا گیم
{% endblock %}

{% block content %}
    <main class="page-content">
        <div class="container">
            <div class="auth-wrapper">
                <div class="auth-form shadow-around">
                    <div class="site-logo">
                        <a href="{% url 'store:home_page' %}">
                            <img src="{{ site_setting.site_header_logo.url }}"
                                 alt="{{ site_setting.site_header_logo_alt }}">
                        </a>
                    </div>
                    <div class="auth-form-title">
                        ثبت نام در همتا
                    </div>
                    <form action="{% url 'accounts:register_page' %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        {#                            <div class="form-element-row">#}
                        {#                                <label class="container-checkbox">#}
                        {#                                    <a href="#" class="link--with-border-bottom">حریم خصوصی</a> و <a href="#" class="link--with-border-bottom">شرایط و قوانین</a> استفاده از سرویس های سایت#}
                        {#                                    همتا را مطالعه نموده#}
                        {#                                    و با کلیه موارد آن موافقم.#}
                        {#                                    <input type="checkbox" checked="checked">#}
                        {#                                    <span class="checkmark"></span>#}
                        {#                                </label>#}
                        {#                            </div>#}
                        <div class="form-element-row text-left">
                            <button type="submit" class="btn-element btn-success-element btn-block mt-2">
                                <i class="fad fa-user-edit"></i>
                                ثبت نام در همتا
                            </button>
                        </div>

                    </form>
                    <div class="auth-form-footer">
                        <span>قبلا در همتا ثبت‌نام کرده‌اید؟</span>
                        <a href="{% url 'accounts:login_page' %}" class="link--with-border-bottom">وارد شوید</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/reset_password_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main class="page-content">
        <div class="container">
            <div class="auth-wrapper">
                <div class="auth-form shadow-around">
                    <div class="site-logo">
                        <a href="{% url 'store:home_page' %}">
                            <img src="{{ site_setting.site_header_logo.url }}"
                                 alt="{{ site_setting.site_header_logo_alt }}">
                        </a>
                    </div>
                    <div class="auth-form-title">
                        یادآوری کلمه عبور
                        {% for field in form %}
                            <p class="text-muted text-center red mb-5">
                                {{ field.errors }}
                            </p>
                        {% endfor %}
                    </div>

                    <form action="{% url 'accounts:reset_password_email' %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <div class="form-element-row text-left mt-3">
                            <button type="submit" class="btn-element btn-success-element">
                                <i class="fad fa-sync"></i>
                                یادآوری کلمه عبور
                            </button>
                        </div>

                    </form>
                    <div class="auth-form-footer">
                        <span>کاربر جدید هستید؟</span>
                        <a href="{% url 'accounts:register_page' %}" class="link--with-border-bottom">ثبت نام در همتا</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/verify_code_auth.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block window_title %}{% endblock %}</title>
    <!-- font-awesome -->
    <link rel="stylesheet" href="{% static '' %}css/font-awesome.min.css">
    <!-- Bootstrap 4.5.3 -->
    <link rel="stylesheet" href="{% static '' %}bootstrap/css/bootstrap.min.css">
    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{% static '' %}css/plugins/apexcharts.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/jquery.classycountdown.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/nouislider.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/sweetalert2.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/select2.min.css">
    <link rel="stylesheet" href="{% static '' %}css/plugins/swiper.min.css">
    <!-- CSS Template -->
    <link rel="stylesheet" href="{% static '' %}css/theme.css">
    <!-- Here goes your custom.css -->
    <link rel="stylesheet" href="{% static '' %}css/custom.css">
    <!-- colors: amber,blue,brown,cyan,default,green,indigo,orange,pink,purple,red,teal,yellow -->
    <link rel="stylesheet" href="{% static '' %}css/colors/default.css" id="colorswitch">
</head>

<body>

<div class="page-wrapper">
    {% include 'messages.html' %}
    <main class="page-content">
        <div class="container">
            <div class="auth-wrapper">
                <div class="auth-form shadow-around">
                    <div class="auth-form-title">
                        تایید کد
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-element-row text-left">
                            <button type="submit" class="btn-element btn-info-element btn-block mt-3">
                                <i class="fad fa-sign-in-alt"></i>
                                تایید کد
                            </button>
                            <a href="{% url 'accounts:resent_sms' %}" class="mt-3 fa-pull-right">
                                ارسال دوباره کد فعالسازی
                            </a>
                            <a href="{% url 'store:home_page' %}" class="mt-3 fa-pull-left">
                                بازگشت به سایت
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
</div>


<!-- JS Global Compulsory -->
<script src="{% static '' %}js/jquery-3.5.1.min.js"></script>
<script src="{% static '' %}js/plugins/popper.min.js"></script>
<script src="{% static '' %}bootstrap/js/bootstrap.min.js"></script>
<!-- JS Implementing Plugins -->
<script src="{% static '' %}js/plugins/apexcharts.min.js"></script>
<script src="{% static '' %}js/plugins/jquery.knob.js"></script>
<script src="{% static '' %}js/plugins/jquery.throttle.js"></script>
<script src="{% static '' %}js/plugins/jquery.classycountdown.min.js"></script>
<script src="{% static '' %}js/plugins/jquery.nicescroll.min.js"></script>
<script src="{% static '' %}js/plugins/nouislider.min.js"></script>
<script src="{% static '' %}js/plugins/sweetalert2.all.min.js"></script>
<script src="{% static '' %}js/plugins/select2.full.min.js"></script>
<script src="{% static '' %}js/plugins/swiper.min.js"></script>
<script src="{% static '' %}js/plugins/ResizeSensor.min.js"></script>
<script src="{% static '' %}js/plugins/theia-sticky-sidebar.min.js"></script>
<script src="{% static '' %}js/plugins/zoomsl.min.js"></script>
<script src="{% static '' %}js/plugins/wNumb.js"></script>
<!-- JS Template -->
<script src="{% static '' %}js/theme.js"></script>
<!-- Here goes your custom.js -->
<script src="{% static '' %}js/custom.js"></script>

<script>
    $(document).ready(function () {
        $('#countdown--offer-slider').ClassyCountdown({
            theme: "black",
            end: $.now() + 645600,
            labels: false,
        });
    });
</script>
</body>

</html>