accounts/urls.py
from django.urls import path
from . import views
from .forms import ResetPasswordEmailValidation

app_name = 'accounts'
urlpatterns = [
    # authenticate
    path('register', views.RegisterView.as_view(), name='register_page'),
    path('register-verify', views.verify_register, name='verify_register'),
    path('resend-sms', views.resent_sms, name='resent_sms'),
    path('login', views.LoginView.as_view(), name='login_page'),
    path('logout', views.LogoutView.as_view(), name='logout_page'),

    # reset password phone
    path('forgot-password', views.forgot_password, name='forgot_password'),
    path('reset-password/<user_temp_code>', views.reset_password, name='reset_password'),

    # change password
    path('change-password', views.ChangePasswordView.as_view(), name='change_password'),

    # reset password email
    path('reset', views.ResetPasswordView.as_view(form_class=ResetPasswordEmailValidation),
         name='reset_password_email'),
    path('reset/done', views.ResetPasswordDoneView.as_view(), name='reset_password_done_email'),
    path('confirm/<uidb64>/<token>/', views.ResetPasswordConfirmView.as_view(), name='reset_password_confirm_email'),
    path('confirm/done', views.ResetPasswordCompleteView.as_view(), name='reset_password_complete_email'),

    # profile
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('orders', views.OrderListView.as_view(), name='order_list'),
    path('favourite', views.FavouriteListView.as_view(), name='favourite'),
    path('comments', views.CommentsListView.as_view(), name='comments'),
    path('comments/<commentId>', views.comment_delete, name='comment_delete'),
    path('profile-info', views.ProfileInfoView.as_view(), name='profile_info'),
    # path('order-detail', views.OrderDetailView.as_view(), name='order_detail'),

    # delete order by user
    path('order-delete/<orderId>', views.order_delete, name='order_delete'),
    path('order-update/<orderId>', views.order_update, name='order_update'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('mag', views.BlogHome.as_view(), name='blog_home'),
    path('mag/<article_slug>', views.blog_detail, name='blog_detail'),
    path('mag/category/<categorySlug>', views.BlogCategoryListView.as_view(), name='blog_category_list'),
    path('mag/tag/<tagSlug>', views.BlogTagListView.as_view(), name='blog_tag_list'),
    path('mag/search/', views.BlogSearchListView.as_view(), name='blog_search_list'),
    path('mag/add-commet/<articleId>', views.add_blog_comment, name='add_blog_comment'),
    path('mag/add-article-comment-reply/<int:articleId>/<int:commentId>', views.add_blog_comment_reply,
         name='add_blog_comment_reply'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from services.sitemaps import *

sitemaps = {
    'homes': HomesViewSitemap,
    'product': ProductViewSitemap,
    'article': ArticleViewSitemap,
}



urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('ticket.urls', namespace='ticket')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('compare.urls', namespace='compare')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.home, name='home_page'),
    path('product/<product_slug>', views.product_detail, name='product_detail_page'),
    path('comment/<productId>', views.product_comment, name='product_comment'),
    path('like_comment/<commentId>', views.comment_like, name='comment_like'),
    path('dislike_comment/<commentId>', views.comment_dislike, name='comment_dislike'),
    path('category/<category_slug>', views.category_list, name='category_list'),
    path('tag/<tag_slug>', views.tag_list, name='tag_list'),
    path('brand/<brand_slug>', views.brand_list, name='brand_list'),
    path('search/', views.SearchListView.as_view(), name='search'),
    # favourite products
    path('favourite/<productSlug>', views.favourite_product, name='favourite_product'),
]

ticket/urls.py
from django.urls import path
from . import views

app_name = 'ticket'
urlpatterns = [
    path('tickets', views.TicketListView.as_view(), name='ticket_list'),
    path('new-ticket', views.NewTicketView.as_view(), name='new_ticket'),
    path('ticket/<ticket_pk>', views.TickerChatView.as_view(), name='ticket_chat'),
    path('send-ticket', views.SendTicketView.as_view(), name='send_ticket'),
    path('ticket-reply/<ticket_pk>', views.SendReplyView.as_view(), name='ticket_reply'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .manager import UserManager
from django.core.validators import RegexValidator
from services.utils import jalali_converter

# regex phone number
phone_number_validation = RegexValidator(
    regex=r'^[0][9]\d{9}$',
    message='لطفا یک شماره همراه معتبر وارد کنید.'
)


class User(AbstractBaseUser):
    first_name = models.CharField(max_length=250, verbose_name='نام')
    last_name = models.CharField(max_length=250, verbose_name='نام خانوادگی')
    email = models.EmailField(max_length=250, unique=True, verbose_name='ایمیل')
    image = models.ImageField(upload_to='user-images', null=True, blank=True, verbose_name='تصویر کاربر')
    province = models.CharField(max_length=100, null=True, blank=True, verbose_name='استان')
    city = models.CharField(max_length=150, null=True, blank=True, verbose_name='شهر')
    phone = models.CharField(max_length=11, validators=[phone_number_validation],
                             unique=True,
                             verbose_name='شماره تلفن')
    post_code = models.CharField(max_length=12, null=True, blank=True, verbose_name='کد پستی')
    address = models.CharField(max_length=300, null=True, blank=True, verbose_name='آدرس')
    is_superuser = models.BooleanField(default=False, verbose_name='مدیر')
    is_news_letter = models.BooleanField(default=False, verbose_name='عضویت در خبرنامه')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیر فعال')
    is_verify = models.BooleanField(default=False, verbose_name='تایید شده / نشده')
    is_admin = models.BooleanField(default=False, verbose_name='ادمین')
    is_editor = models.BooleanField(default=False, verbose_name='نویسنده ارشد')
    has_setting_access = models.BooleanField(default=False, verbose_name='دسترسی به تنظیمات')
    is_writer = models.BooleanField(default=False, verbose_name='نویسنده')
    temp_code = models.CharField(max_length=255, null=True, blank=True, verbose_name='کد موقت')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')
    updated_date = models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')

    objects = UserManager()

    USERNAME_FIELD = 'phone'
    # fields required for admin
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def jalali_created_date(self):
        return jalali_converter(self.created_date)

    jalali_created_date.short_description = 'تاریخ انتشار'

    def has_perm(self, perm, obj=None):
        # if self.is_superuser:
        return True

    def has_module_perms(self, app_label):
        return True
        # if app_label == 'users_account':
        #     if self.is_superuser:
        #         return True
        # elif app_label == 'store':
        #     if self.is_superuser or self.is_admin:
        #         return True
        # elif app_label == 'order':
        #     if self.is_superuser or self.is_admin:
        #         return True
        # elif app_label == 'slider':
        #     if self.is_superuser or self.is_admin:
        #         return True
        # elif app_label == 'site_setting':
        #     if self.is_superuser or self.is_admin:
        #         return True
        # elif app_label == 'blog':
        #     if self.is_superuser or self.is_admin or self.is_writer or self.is_editor:
        #         return True

    @property
    def is_staff(self):
        if self.is_superuser:
            return True
        elif self.is_admin:
            return True
        elif self.is_writer:
            return True
        elif self.is_editor:
            return True

    def full_name(self):
        if self.first_name and self.last_name:
            return f'{self.first_name} {self.last_name}'
        else:
            return self.email

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربران'

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from ckeditor_uploader.fields import RichTextUploadingField

User = get_user_model()


class BlogCategory(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True,
                               verbose_name='زیر دسته')
    name = models.CharField(max_length=200, verbose_name='نام دسته بندی')
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, verbose_name='آدرس url')
    blog_category_meta_description = models.TextField(max_length=200, blank=True, null=True,
                                                      verbose_name='توضیحات متا')
    blog_category_meta_keywords = models.TextField(max_length=200, blank=True, null=True,
                                                   verbose_name='کلمه های کلیدی')
    status = models.BooleanField(default=True, verbose_name='نمایش / عدم نمایش')
    meta_description = models.TextField(max_length=300, verbose_name='توضیحات متای صفحه دسته بندی')
    meta_keywords = models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه دسته بندی')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:blog_category_list', args=[self.slug])


class BlogTag(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True, verbose_name='عنوان')
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, verbose_name='آدرس url')
    status = models.BooleanField(default=True, verbose_name='نمایش / عدم نمایش')
    meta_description = models.TextField(max_length=300, verbose_name='توضیحات متای صفحه تگ')
    meta_keywords = models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه تگ')

    class Meta:
        verbose_name = 'تگ / برچسب'
        verbose_name_plural = 'تگ ها / برچسب ها'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_tag_list', args=[self.slug])


class ArticleManager(models.Manager):
    def get_active_articles(self):
        return self.filter(is_active=True)


class Article(models.Model):
    STATUS = (
        ('article', 'مقاله'),
        ('news', 'خبر'),
        ('video', 'فیلم'),
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='نویسنده')
    title = models.CharField(max_length=250, verbose_name='عنوان مقاله')
    article_browser_title = models.CharField(max_length=60, unique=True,
                                             verbose_name='آدرس سایت در مرورگر')
    slug = models.SlugField(max_length=250, unique=True, allow_unicode=True, verbose_name='آدرس url')
    image = models.ImageField(upload_to='images/blog-header/', verbose_name='تصویر شاخص')
    image_alt = models.CharField(max_length=200, verbose_name='متن جایگزین تصویر')
    categories = models.ManyToManyField(BlogCategory, related_name='article', blank=True, verbose_name='دسته بندی')
    tags = models.ManyToManyField(BlogTag, related_name='article', blank=True, verbose_name='تگ / برچسب')
    status = models.CharField(max_length=10, choices=STATUS, default='article', verbose_name='نوع محتوا')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    content = RichTextUploadingField(verbose_name='توضیحات مقاله')
    # article_hits = models.ManyToManyField(User, blank=True, related_name='article_hits',
    #                                       verbose_name='افرادی که از این محتوا بازدید کرده اند')
    # article_num_hits = models.IntegerField(default=0, verbose_name='تعداد بازدید')
    is_active = models.BooleanField(default=False, verbose_name='فعال / غیر فعال')
    has_video = models.BooleanField(default=False, verbose_name='شامل کلیپ است')
    meta_description = models.TextField(max_length=300, verbose_name='توضیحات متای صفحه مقاله')
    meta_keywords = models.TextField(max_length=300, verbose_name='کلمه های کلیدی صفحه مقاله')
    article_robots = models.CharField(max_length=100, default='index,follow', blank=True, null=True,
                                      verbose_name='تگ robots')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')
    updated_date = models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')

    objects = ArticleManager()

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[self.slug])


class BlogComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_blog_comments', verbose_name='کاربر')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='blog_comments',
                                verbose_name='محتوا')
    content = models.TextField(verbose_name='کامنت')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply_blog_comments', null=True,
                              blank=True,
                              verbose_name='پاسخ به کامنت')
    # reply_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_reply_to', blank=True,
    #                              null=True, verbose_name='در پاسخ به')
    is_reply = models.BooleanField(default=False, verbose_name='آیا پاسخ دارد؟')
    is_published = models.BooleanField(default=True, verbose_name='وضعیت انتشار')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'

accounts/templates/accounts/profile/dashboard.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <main class="page-content" style="margin-top: 205.5px; transform: none;">
        <div class="container" style="transform: none;">
            <div class="row mb-5" style="transform: none;">
                {% include 'accounts/profile/sidebar.html' %}
                <div class="col-lg-9 col-md-8">
                    <div class="row mb-4">
                        <div class="col-lg-6 mb-lg-0 mb-3">
                            <div class="section-title mb-2">
                                اطلاعات شخصی
                            </div>
                            <section class="shadow-around p-3">
                                <div class="row">
                                    <div class="col-lg-6 mb-4">
                                        <div class="text-sm text-muted">نام و نام خانوادگی:</div>
                                        <div class="text-dark font-weight-bold">{{ request.user.full_name }}</div>
                                    </div>
                                    <div class="col-lg-6 mb-4">
                                        <div class="text-sm text-muted">پست الکترونیک:</div>
                                        <div class="text-dark font-weight-bold">{{ request.user.email }}</div>
                                    </div>
                                    <div class="col-lg-6 mb-4">
                                        <div class="text-sm text-muted">شماره تلفن همراه:</div>
                                        <div class="text-dark font-weight-bold">{{ request.user.phone }}</div>
                                    </div>
                                    <div class="col-lg-6 mb-4">
                                        <div class="text-sm text-muted">استان:</div>
                                        <div class="text-dark font-weight-bold">
                                            {% if request.user.province %}
                                                {{ request.user.province }}
                                            {% else %}
                                                لطفا استان خود را وارد کنید.
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mb-4">
                                        <div class="text-sm text-muted">شهر:</div>
                                        <div class="text-dark font-weight-bold">
                                            {% if request.user.city %}
                                                {{ request.user.city }}
                                            {% else %}
                                                لطفا شهر خود را وارد کنید.
                                            {% endif %}
                                        </div>
                                    </div>
                                    {#                                    <div class="col-lg-6 mb-4">#}
                                    {#                                        <div class="text-sm text-muted">دریافت خبرنامه:</div>#}
                                    {#                                        <div class="text-dark font-weight-bold">خیر</div>#}
                                    {#                                    </div>#}
                                    <div class="col-12">
                                        <div class="text-center">
                                            <a href="{% url 'accounts:profile_info' %}"
                                               class="link--with-border-bottom">
                                                <i class="far fa-edit"></i>
                                                ویرایش اطلاعات شخصی
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </section>
                        </div>
                        <div class="col-lg-6 mb-lg-0 mb-3">
                            <div class="section-title mb-2">
                                لیست آخرین علاقه‌مندی‌ها
                            </div>
                            <section class="shadow-around p-3">
                                <div class="row">

                                    {% for product in favorite_products %}
                                        <div class="col-12 mb-4">
                                            <div class="product-list-section">
                                                <div class="product-thumbnail">
                                                    <a href="{{ product.get_absolute_url }}">
                                                        <img src="{{ product.image.url }}"
                                                             alt="product title">
                                                    </a>
                                                </div>
                                                <div class="product-info">
                                                    <div class="product-title">
                                                        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                                    </div>
                                                    <div class="text-danger">
                                                        {{ product.total_price|intcomma:False }}
                                                        <span class="text-sm">تومان</span>
                                                    </div>
                                                    <form action="{% url 'store:favourite_product' product.slug %}">
                                                        <button type="submit" class="remove-item">
                                                            <i class="far fa-trash-alt"></i>
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    {% empty %}
                                        <div class="col-12">
                                            <div class="text-center">
                                            <span class="link--with-border-bottom">
                                                <i class="far fa-heart"></i>
                                                در حال حاضر محصولی را به لیست علاقه مندی خود اضافه نکرده اید.
                                            </span>
                                            </div>
                                        </div>
                                    {% endfor %}
                                    {% if favorite_products %}
                                        <div class="col-12">
                                            <div class="text-center">
                                                <a href="{% url 'accounts:favourite' %}"
                                                   class="link--with-border-bottom">
                                                    <i class="far fa-edit"></i>
                                                    مشاهده و ویرایش لیست مورد علاقه
                                                </a>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/profile/sidebar.html
{% load static %}
<div class="col-lg-3 col-md-4 mb-md-0 mb-3 sticky-sidebar"
     style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">

    <div class="theiaStickySidebar"
         style="padding-top: 0px; padding-bottom: 1px; position: static; transform: none; left: 658.2px; top: 0px;">
        <div class="sidebar-widget">
            <div class="banner mb-3">
                <div class="profile-avatar text-center">
                    <img src="/static/images/avatar/avatar.png" alt="avatar">
                </div>
            </div>
            <div class="profile-sidebar shadow-around">
                <div class="user-menu">
                    {% with url_name=request.resolver_match.url_name %}
                        <ul>
                            <li>
                                <a href="{% url 'accounts:dashboard' %}"
                                   {% if url_name == 'dashboard' %}class="active" {% endif %}>
                                    <i class="far fa-home"></i>
                                    داشبورد
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:order_list' %}"
                                   {% if url_name == 'order_list' %}class="active"{% endif %}>
                                    <i class="far fa-clipboard-list-check"></i>
                                    سفارش های من
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:favourite' %}"
                                   {% if url_name == 'favourite' %}class="active"{% endif %}>
                                    <i class="far fa-heart"></i>
                                    لیست علاقمندی
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:comments' %}"
                                   {% if url_name == 'comments' %}class="active"{% endif %}>
                                    <i class="far fa-comment-alt-lines"></i>
                                    نظرات
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'ticket:ticket_list' %}"
                                   {% if url_name == 'ticket' %}class="active"{% endif %}>
                                    <i class="far fa-envelope"></i>
                                    تیکت ها
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:profile_info' %}"
                                   {% if url_name == 'profile_info' %}class="active"{% endif %}>
                                    <i class="far fa-user-cog"></i>
                                    اطلاعات حساب
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:change_password' %}"
                                   {% if url_name == 'change_password' %}class="active"{% endif %}>
                                    <i class="far fa-user-lock"></i>
                                    تغییر رمز عبور
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:logout_page' %}">
                                    <i class="far fa-sign-in-alt"></i>
                                    خروج
                                </a>
                            </li>
                        </ul>
                    {% endwith %}
                </div>
            </div>
        </div>
        <div class="resize-sensor"
             style="position: absolute; inset: 0px; overflow: hidden; z-index: -1; visibility: hidden;">
            <div class="resize-sensor-expand"
                 style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
                <div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 332px; height: 1721px;"></div>
            </div>
            <div class="resize-sensor-shrink"
                 style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
                <div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div>
            </div>
        </div>
    </div>
</div>

accounts/templates/accounts/profile/ticket_list.html
{% extends 'base.html' %}

{% block content %}
    <main class="page-content" style="margin-top: 205.5px; transform: none;">
        <div class="container" style="transform: none;">
            <div class="row mb-5" style="transform: none;">
                {% include 'accounts/profile/sidebar.html' %}
                <div class="col-lg-9 col-md-8 col-xs-9">
                    <div class="section-title mb-2">
                        تیکت های من
                    </div>
                    <div class="shadow-around">
                        <div class="listing-items row">
                            <div class="alert alert-primary col-12 m-0" role="alert">
                                <h4 class="alert-heading">لیست تیکت های شما</h4>
                                <p>در این قسمت میتوانید با ارسال تیکت با ما در ارتباط باشید.</p>
                                <div class="form-submit col-md-12">
                                    <a href="{% url 'ticket:new_ticket' %}" class="btn btn-success">ثبت تیکت جدید</a>
                                </div>
                            </div>
                            {% if tickets %}
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th scope="col">عنوان تیکت</th>
                                        <th scope="col">ایمیل</th>
                                        <th scope="col">وضعیت</th>
                                        <th scope="col">تاریخ ثبت تیکت</th>
                                        <th scope="col">مشاهده</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for ticket in tickets %}
                                        <tr>
                                            <td>{{ ticket.title }}</td>
                                            <td>{{ request.user.email }}</td>
                                            <td>{{ ticket.get_status_display }}</td>
                                            <td>{{ ticket.jalali_created_date }}</td>
                                            <td>
                                                <a href="{% url 'ticket:ticket_chat' ticket.id %}"
                                                   class="btn btn-success">مشاهده</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <div class="alert alert-error" role="alert">
                                    <h4 class="alert-heading">در حال حاضر هیچ تیکتی ارسال نکرده اید.</h4>
                                    <p>برای ارسال تیکت گزینه ثبت تیکت جدید را کلیک کنید.</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}