blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('mag', views.BlogHome.as_view(), name='blog_home'),
    path('mag/<article_slug>', views.blog_detail, name='blog_detail'),
    path('mag/category/<categorySlug>', views.BlogCategoryListView.as_view(), name='blog_category_list'),
    path('mag/tag/<tagSlug>', views.BlogTagListView.as_view(), name='blog_tag_list'),
    path('mag/search/', views.BlogSearchListView.as_view(), name='blog_search_list'),
    path('mag/add-commet/<articleId>', views.add_blog_comment, name='add_blog_comment'),
    path('mag/add-article-comment-reply/<int:articleId>/<int:commentId>', views.add_blog_comment_reply,
         name='add_blog_comment_reply'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from services.sitemaps import *

sitemaps = {
    'homes': HomesViewSitemap,
    'product': ProductViewSitemap,
    'article': ArticleViewSitemap,
}



urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('ticket.urls', namespace='ticket')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('compare.urls', namespace='compare')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('order-paid/<order_id>', views.order_is_paid, name='order_is_paid'),
    path('order-form', views.order_form, name='order_form'),
    path('order-create/', views.order_create, name='order_create'),
    path('order-complete/<order_id>/', views.order_complete, name='order_complete'),

    path('ajax/load-cities', views.load_cities, name='load_cities'),  # ajax load cities

    path('request/<pk>/<price>/', views.send_request_payment, name='request_payment'),
    path('verify/', views.verify, name='verify'),
]

order/models.py
from django.db import models
from accounts.models import User
from store.models import Product, Variants
from services.utils import jalali_converter
from shipping.models import Provinces, Cities


class Order(models.Model):
    STATUS_CHOICES = (
        ('P', 'پرداخت شده'),
        ('S', 'در حال ارسال'),
        ('R', 'تحویل داده شده'),
        ('N', 'پرداخت نشده'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    order_code = models.CharField(max_length=20, unique=True, editable=False, verbose_name='کد پیگیری')
    first_name = models.CharField(max_length=100, verbose_name='نام')
    last_name = models.CharField(max_length=100, verbose_name='نام خانوادگی')
    phone = models.CharField(max_length=11, verbose_name='شماره همراه')
    province = models.ForeignKey(Provinces, on_delete=models.CASCADE, verbose_name='استان')
    city = models.ForeignKey(Cities, on_delete=models.CASCADE, verbose_name='شهر')
    address = models.CharField(max_length=250, verbose_name='آدرس')
    discount = models.PositiveIntegerField(null=True, blank=True, verbose_name='تخفیف')
    total = models.PositiveBigIntegerField(null=True, blank=True, verbose_name='قیمت نهایی')
    is_paid = models.BooleanField(default=False, verbose_name='پرداخت')
    admin_note = models.CharField(max_length=150, blank=True, verbose_name='یادداشت مدیر')
    order_description = models.TextField(max_length=500, blank=True, verbose_name='توضیحات سفارش')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, verbose_name='وضعیت سفارش')
    shipping_price = models.PositiveBigIntegerField(null=True, blank=True, verbose_name='هزینه حمل و نقل')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش ها'

    def jalali_created_date(self):
        return jalali_converter(self.created_date)

    jalali_created_date.short_description = 'تاریخ سفارش'

    @property
    def total(self):
        total = sum(item.get_price() for item in self.item_orders.all())
        total += self.shipping_price
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total

    def get_day_total(self):
        day_total = sum(item.get_day_price() for item in self.item_orders.all())
        day_total += self.shipping_price
        if self.discount:
            discount_price = (self.discount / 100) * day_total
            return int(day_total - discount_price) * 10
        return day_total * 10

    def get_day_total_for_user(self):
        day_total = sum(item.get_day_price() for item in self.item_orders.all())
        day_total += self.shipping_price
        if self.discount:
            discount_price = (self.discount / 100) * day_total
            return int(day_total - discount_price)
        return day_total

    def number(self):
        return f'HG-{self.user.id}-{self.id}'

    number.short_description = 'شماره سفارش'


class ItemOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='item_orders',
                              verbose_name='سفارش')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    variant = models.ForeignKey(Variants, null=True, blank=True, on_delete=models.CASCADE, verbose_name='نوع محصول')
    console_guarantee = models.CharField(max_length=200, null=True, blank=True, verbose_name='گارانتی کنسول')
    controller_guarantee = models.CharField(max_length=200, null=True, blank=True, verbose_name='گارانتی دسته')
    unit_price = models.PositiveBigIntegerField(null=True, blank=True, verbose_name='قیمت واحد بدون تخفیف')
    unit_price_with_discount = models.PositiveBigIntegerField(null=True, blank=True, verbose_name='قیمت واحد با تخیف')
    discount = models.IntegerField(null=True, blank=True, verbose_name='تخفیف')
    quantity = models.IntegerField(null=True, blank=True, verbose_name='تعداد')
    price = models.PositiveBigIntegerField(null=True, blank=True, verbose_name='قیمت تمام شده')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = 'جزییات سفارش'
        verbose_name_plural = 'جزییات سفارش ها'

    def jalali_created_date(self):
        return jalali_converter(self.created_date)

    jalali_created_date.short_description = 'تاریخ سفارش'

    def get_price(self):
        return self.price * self.quantity

    def get_total(self):
        return self.order.total

    def get_day_price(self):
        return self.variant.total_price * self.quantity

    @property
    def title(self):
        return self.variant.product_variant.title

    title.fget.short_description = 'نام محصول'

    def unit_price_discount(self):
        if not self.discount:
            return self.unit_price
        elif self.discount:
            total = (self.unit_price * self.discount) / 100
            return int(self.unit_price - total)

    unit_price_discount.short_description = 'قیمت واحد با تخفیف'

    def sub_total(self):
        if self.price and self.quantity:
            sub_total = int(self.price * self.quantity)
            return sub_total
        else:
            return None

    sub_total.short_description = 'قیمت تمام شده'

order/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import *
from .forms import OrderForm
from cart.cart import Cart
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
from store.models import *
from django.contrib import messages
import requests
import json
from core.settings import MERCHANT
from shipping.models import WeightPrice


@login_required
def order_form(request):
    cart = Cart(request)
    if not cart:
        return redirect('/')
    form = OrderForm()
    provinces = Provinces.objects.all()
    return render(request, 'order/order_form.html', {'form': form, 'provinces': provinces})


def order_create(request):
    form = OrderForm(request.POST or None)
    if request.user.is_authenticated and request.user.is_verify:
        if request.method == 'POST':
            cart = Cart(request)
            if cart:
                if form.is_valid():
                    data = form.cleaned_data
                    order = Order.objects.create(
                        user_id=request.user.id,
                        province=data['province'],
                        city=data['city'],
                        address=data['address'], phone=data['phone'], first_name=data['first_name'],
                        last_name=data['last_name'], order_description=data['order_description'],
                        status='not_paid',
                        order_code=get_random_string(length=10)
                    )
                    obj_weight = 0
                    for data in cart:
                        obj_weight += int(data['variant'].product.weight * data['quantity'])

                    # total_weight_price(order, total_weight)
                    weight_price = WeightPrice.objects.last()
                    if obj_weight <= 500:
                        order.shipping_price = int(weight_price.price_0_to_half)
                        order.save()
                    elif obj_weight > 500 and obj_weight <= 1000:
                        order.shipping_price = int(weight_price.price_half_to_1)
                        order.save()
                    elif obj_weight > 1000 and obj_weight <= 2000:
                        order.shipping_price = int(weight_price.price_1_to_2)
                        order.save()
                    elif obj_weight > 2000 and obj_weight <= 3000:
                        order.shipping_price = int(weight_price.price_2_to_3)
                        order.save()
                    elif obj_weight > 3000 and obj_weight <= 4000:
                        order.shipping_price = int(weight_price.price_3_to_4)
                        order.save()
                    elif obj_weight > 4000 and obj_weight <= 5000:
                        order.shipping_price = int(weight_price.price_4_to_5)
                        order.save()
                    elif obj_weight > 5000 and obj_weight <= 6000:
                        order.shipping_price = int(weight_price.price_5_to_6)
                        order.save()
                    elif obj_weight > 6000 and obj_weight <= 7000:
                        order.shipping_price = int(weight_price.price_6_to_7)
                        order.save()
                    elif obj_weight > 7000 and obj_weight <= 8000:
                        order.shipping_price = int(weight_price.price_7_to_8)
                        order.save()
                    elif obj_weight > 8000 and obj_weight <= 9000:
                        order.shipping_price = int(weight_price.price_8_to_9)
                        order.save()
                    elif obj_weight > 9000 and obj_weight <= 10000:
                        order.shipping_price = int(weight_price.price_9_to_10)
                        order.save()
                    elif obj_weight > 10000 and obj_weight <= 11000:
                        order.shipping_price = int(weight_price.price_10_to_11)
                        order.save()
                    elif obj_weight > 11000 and obj_weight <= 12000:
                        order.shipping_price = int(weight_price.price_11_to_12)
                        order.save()
                    elif obj_weight > 12000 and obj_weight <= 13000:
                        order.shipping_price = int(weight_price.price_12_to_13)
                        order.save()
                    elif obj_weight > 13000 and obj_weight <= 14000:
                        order.shipping_price = int(weight_price.price_13_to_14)
                        order.save()
                    elif obj_weight > 14000 and obj_weight <= 15000:
                        order.shipping_price = int(weight_price.price_14_to_15)
                        order.save()
                    elif obj_weight > 15000 and obj_weight <= 16000:
                        order.shipping_price = int(weight_price.price_15_to_16)
                        order.save()
                    elif obj_weight > 16000 and obj_weight <= 17000:
                        order.shipping_price = int(weight_price.price_16_to_17)
                        order.save()
                    elif obj_weight > 17000 and obj_weight <= 18000:
                        order.shipping_price = int(weight_price.price_17_to_18)
                        order.save()
                    elif obj_weight > 18000 and obj_weight <= 19000:
                        order.shipping_price = int(weight_price.price_18_to_19)
                        order.save()
                    elif obj_weight > 19000 and obj_weight <= 20000:
                        order.shipping_price = int(weight_price.price_19_to_20)
                        order.save()
                    elif obj_weight > 20000 and obj_weight <= 21000:
                        order.shipping_price = int(weight_price.price_20_to_21)
                        order.save()
                    elif obj_weight > 21000 and obj_weight <= 22000:
                        order.shipping_price = int(weight_price.price_21_to_22)
                        order.save()
                    elif obj_weight > 22000 and obj_weight <= 23000:
                        order.shipping_price = int(weight_price.price_22_to_23)
                        order.save()
                    elif obj_weight > 23000 and obj_weight <= 24000:
                        order.shipping_price = int(weight_price.price_23_to_24)
                        order.save()
                    elif obj_weight > 24000 and obj_weight <= 25000:
                        order.shipping_price = int(weight_price.price_24_to_25)
                        order.save()
                    elif obj_weight > 25000 and obj_weight <= 26000:
                        order.shipping_price = int(weight_price.price_25_to_26)
                        order.save()
                    elif obj_weight > 26000 and obj_weight <= 27000:
                        order.shipping_price = int(weight_price.price_26_to_27)
                        order.save()
                    elif obj_weight > 27000 and obj_weight <= 28000:
                        order.shipping_price = int(weight_price.price_27_to_28)
                        order.save()
                    elif obj_weight > 28000 and obj_weight <= 29000:
                        order.shipping_price = int(weight_price.price_28_to_29)
                        order.save()
                    elif obj_weight > 29000 and obj_weight <= 30000:
                        order.shipping_price = int(weight_price.price_29_to_30)
                        order.save()
                    elif obj_weight > 30000:
                        order.shipping_price = int(weight_price.price_30_to_higher)
                        order.save()

                    for item in cart:
                        ItemOrder.objects.create(
                            user_id=request.user.id,
                            order_id=order.id,
                            variant=item['variant'],
                            price=item['variant'].total_price,
                            console_guarantee=item['variant'].console_variant,
                            controller_guarantee=item['variant'].controller_variant,
                            unit_price=item['variant'].unit_price,
                            discount=item['variant'].discount_variant,
                            quantity=item['quantity']
                        )
                    cart.clear()
                    return redirect('order:order_complete', order.id)
            else:
                messages.warning(request, 'سبد خرید شما خالی است!')
                return redirect('/')
        else:
            return redirect('store:home_page')
    else:
        return redirect('/')


@login_required
def order_complete(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    # check if order is for this user and is not paid then show the payment page
    if request.user.id == order.user_id and not order.is_paid:
        return render(request, 'order/order_complete.html', {'order': order})
    # check if order is for this user and if it`s paid then redirect user
    elif request.user.id == order.user.id and order.is_paid:
        messages.info(request, f'سفارش {order.order_code} برای شما پرداخت شده است.')
        return redirect('accounts:order_list')
    else:
        return redirect('store:home_page')


def load_cities(request):
    province_id = request.GET.get('province_id')
    cities = Cities.objects.filter(province_id=province_id)
    return render(request, 'order/cities_list_options.html', {'cities': cities})


@login_required
def order_is_paid(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.user.id == order.user_id:
        items = order.item_orders.all()
        return render(request, 'order/order_is_paid.html', {'order': order, 'items': items})
    else:
        return redirect('store:home')


MERCHANT = MERCHANT
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"

order/templates/order/cities_list_options.html
<option value="">انتخاب شهر</option>
{% for city in cities %}
    <option value="{{ city.pk }}">{{ city.fa_name }}</option>
{% endfor %}

order/templates/order/order_complete.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <main class="page-content" style="margin-top: 205.5px;">
        <div class="container">
            <div class="row mb-4">
                <div class="col-xl-9 col-lg-8 col-md-8 mb-md-0 mb-3">
                    <div class="checkout-section shadow-around">
                        <div class="checkout-message">
                            <div class="checkout-message-success mb-3">
                                <div class="icon-message success-icon">
                                    <i class="fas fa-check"></i>
                                </div>
                                سفارش شما با موفقیت ثبت گردید.
                                <br>
                                کد پیگیری سفارش شما: <span class="order-code">{{ order.order_code }}</span>
                            </div>
                            <div class="text-center text-muted">
                                <p class="mb-4">
                                    کاربر گرامی، {{ request.user.username }} سفارش شما با موفقیت ثبت گردید. برای پرداخت
                                    و ثبت نهایی روی گزینه پرداخت کلیک کنید.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4 col-md-4">
                    <div class="shadow-around pt-3">
                        <div class="d-flex justify-content-between px-3 py-2">
                            <span class="text-muted">نام تحویل گیرنده:</span>
                            <span class="text-muted">
                                    {{ order.user.full_name }}
                                </span>
                        </div>
                        <div class="d-flex justify-content-between px-3 py-2">
                            <span class="text-muted">شماره تماس :</span>
                            <span class="text-danger">
                                    {{ order.user.phone }}
                                </span>
                        </div>
                        <div class="d-flex justify-content-between px-3 py-2">
                            <span class="text-muted">هزینه حمل و نقل :</span>
                            <span class="text-danger">
                                    {{ order.shipping_price|intcomma:False }} تومان
                                </span>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-between px-3 py-2">
                            <span class="font-weight-bold">مبلغ کل:</span>
                            <span class="font-weight-bold">
                                    {{ order.total|intcomma:False }}
                                    <span class="text-sm">تومان</span>
                                </span>
                        </div>
                        <hr>
                        <div class="px-3 py-2">
                            <span class="text-muted d-block">آدرس :</span>
                            <span class="text-info">
                                    {{ order.province }}
                                    {{ order.city }}
                                    {{ order.address }}
                                </span>
                        </div>
                        <div class="px-3 py-4">
                            <a href="{% url 'order:request_payment' order.id order.get_day_total %}"
                               class="d-flex align-items-center justify-content-center px-4 py-2 btn btn-primary">
                                پرداخت
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

order/templates/order/order_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}



    <main class="page-content" style="margin-top: 205.5px;">
        <div class="container">
            <div class="row mb-4">
                <div class="col-xl-12 col-lg-12 col-md-12 mb-md-0 mb-3">
                    <div class="checkout-section shadow-around">
                        <div class="checkout-section-content">
                            <div class="checkout-section-title text-center">آدرس تحویل سفارش</div>
                            <div class="col-12">
                                <form id="order-form" action="{% url 'order:order_create' %}"
                                      data-cities-url="{% url 'order:load_cities' %}" method="post">
                                    {% csrf_token %}
                                    <div class="col-6 m-auto">
                                        {% render_field form.first_name class="form-control" placeholder='نام' %}
                                        {% render_field form.last_name class="form-control mt-3" placeholder='نام خانوادگی' %}
                                        {% render_field form.phone class="form-control mt-3" placeholder='شماره همراه' %}
                                        {% render_field form.province class="form-control mt-3" placeholder='استان' %}
                                        {% render_field form.city class="form-control mt-3" placeholder='شهر' %}
                                        {% render_field form.address class="form-control mt-3" placeholder='آدرس' %}
                                        {% render_field form.order_description class="form-control mt-3" placeholder="توضیحات" %}
                                        <button type="submit" class="btn btn-success mt-3 btn-block">ثبت اطلاعات ارسال
                                        </button>
                                    </div>

                                </form>
                            </div>
                            <div class="checkout-section-title">شیوه پرداخت</div>
                            <div class="payment-selection">
                                <div class="custom-control custom-radio custom-control-inline mb-3">
                                    <input type="radio" id="paymentSelection1" name="paymentSelection"
                                           class="custom-control-input" checked="">
                                    <label class="custom-control-label payment-select" for="paymentSelection1">
                                            <span class="d-flex align-items-center">
                                                <i class="fad fa-credit-card"></i>
                                                <span>
                                                    <span class="title">پرداخت اینترنتی</span>
                                                    <span class="subtitle">آنلاین با تمامی کارت‌های بانکی</span>
                                                </span>
                                            </span>
                                    </label>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline mb-3">
                                    <input type="radio" id="paymentSelection2" name="paymentSelection"
                                           class="custom-control-input">
                                    <label class="custom-control-label payment-select" for="paymentSelection2">
                                            <span class="d-flex align-items-center">
                                                <i class="fad fa-map-marker-alt"></i>
                                                <span>
                                                    <span class="title">پرداخت در محل</span>
                                                    <span class="subtitle">پرداخت درب منزل</span>
                                                </span>
                                            </span>
                                    </label>
                                </div>
                            </div>
                            <hr>
                            <div class="row mx-0">
                                <div class="col-md-6">
                                    <div class="checkout-section-title">کد تخفیف</div>
                                    <form action="#">
                                        <div class="d-flex align-items-center">
                                            <div class="form-element-row flex-grow-1">
                                                <input type="text" class="input-element" id="phone-number"
                                                       placeholder="کد تخفیف را وارد کنید">
                                            </div>
                                            <div class="form-element-row mr-3">
                                                <button class="btn-element btn-info-element">
                                                    <i class="fad fa-sync"></i>
                                                    ثبت
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-6">
                                    <div class="checkout-section-title">کارت هدیه</div>
                                    <form action="#">
                                        <div class="d-flex align-items-center">
                                            <div class="form-element-row flex-grow-1">
                                                <input type="text" class="input-element" id="phone-number"
                                                       placeholder="کد مربوط به کارت هدیه را وارد کنید">
                                            </div>
                                            <div class="form-element-row mr-3">
                                                <button class="btn-element btn-info-element">
                                                    <i class="fad fa-sync"></i>
                                                    ثبت
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </main>
    <script src="/static/js/jquery-3.5.1.min.js"></script>
    <script>
        $("#id_province").change(function () {
            const url = $("order-form").attr("data-cities-url");
            const provinceId = $(this).val();

            $.ajax({
                url: '{% url "order:load_cities" %}',
                data: {
                    'province_id': provinceId
                },
                success: function (data) {
                    $("#id_city").html(data);
                }
            })
        })
    </script>

{% endblock %}