accounts/urls.py
from django.urls import path
from . import views
from .forms import ResetPasswordEmailValidation

app_name = 'accounts'
urlpatterns = [
    # authenticate
    path('register', views.RegisterView.as_view(), name='register_page'),
    path('register-verify', views.verify_register, name='verify_register'),
    path('resend-sms', views.resent_sms, name='resent_sms'),
    path('login', views.LoginView.as_view(), name='login_page'),
    path('logout', views.LogoutView.as_view(), name='logout_page'),

    # reset password phone
    path('forgot-password', views.forgot_password, name='forgot_password'),
    path('reset-password/<user_temp_code>', views.reset_password, name='reset_password'),

    # change password
    path('change-password', views.ChangePasswordView.as_view(), name='change_password'),

    # reset password email
    path('reset', views.ResetPasswordView.as_view(form_class=ResetPasswordEmailValidation),
         name='reset_password_email'),
    path('reset/done', views.ResetPasswordDoneView.as_view(), name='reset_password_done_email'),
    path('confirm/<uidb64>/<token>/', views.ResetPasswordConfirmView.as_view(), name='reset_password_confirm_email'),
    path('confirm/done', views.ResetPasswordCompleteView.as_view(), name='reset_password_complete_email'),

    # profile
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('orders', views.OrderListView.as_view(), name='order_list'),
    path('favourite', views.FavouriteListView.as_view(), name='favourite'),
    path('comments', views.CommentsListView.as_view(), name='comments'),
    path('comments/<commentId>', views.comment_delete, name='comment_delete'),
    path('profile-info', views.ProfileInfoView.as_view(), name='profile_info'),
    # path('order-detail', views.OrderDetailView.as_view(), name='order_detail'),

    # delete order by user
    path('order-delete/<orderId>', views.order_delete, name='order_delete'),
    path('order-update/<orderId>', views.order_update, name='order_update'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('mag', views.BlogHome.as_view(), name='blog_home'),
    path('mag/<article_slug>', views.blog_detail, name='blog_detail'),
    path('mag/category/<categorySlug>', views.BlogCategoryListView.as_view(), name='blog_category_list'),
    path('mag/tag/<tagSlug>', views.BlogTagListView.as_view(), name='blog_tag_list'),
    path('mag/search/', views.BlogSearchListView.as_view(), name='blog_search_list'),
    path('mag/add-commet/<articleId>', views.add_blog_comment, name='add_blog_comment'),
    path('mag/add-article-comment-reply/<int:articleId>/<int:commentId>', views.add_blog_comment_reply,
         name='add_blog_comment_reply'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add-to-cart', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<variant_id>', views.remove_from_cart, name='remove_from_cart'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from services.sitemaps import *

sitemaps = {
    'homes': HomesViewSitemap,
    'product': ProductViewSitemap,
    'article': ArticleViewSitemap,
}



urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('ticket.urls', namespace='ticket')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('compare.urls', namespace='compare')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.home, name='home_page'),
    path('product/<product_slug>', views.product_detail, name='product_detail_page'),
    path('comment/<productId>', views.product_comment, name='product_comment'),
    path('like_comment/<commentId>', views.comment_like, name='comment_like'),
    path('dislike_comment/<commentId>', views.comment_dislike, name='comment_dislike'),
    path('category/<category_slug>', views.category_list, name='category_list'),
    path('tag/<tag_slug>', views.tag_list, name='tag_list'),
    path('brand/<brand_slug>', views.brand_list, name='brand_list'),
    path('search/', views.SearchListView.as_view(), name='search'),
    # favourite products
    path('favourite/<productSlug>', views.favourite_product, name='favourite_product'),
]

templates/base.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block window_title %}{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    <meta name="robots" content="{% block meta_robots %}{% endblock %}"/>
    <link rel="canonical" href="{% block link_canonical %}{% endblock %}"/>
    <!--favicon icon-->
    <link rel="icon" href="{{ site_setting.site_favicon_logo.url }}" type="image/png" sizes="16x16">
    {% compress css %}
        <!-- font-awesome -->
        <link rel="stylesheet" href="{% static '' %}css/font-awesome.min.css">
        <!-- Bootstrap 4.5.3 -->
        <link rel="stylesheet" href="{% static '' %}bootstrap/css/bootstrap.min.css">
        <!-- CSS Implementing Plugins -->
        <link rel="stylesheet" href="{% static '' %}css/plugins/apexcharts.css">
        <link rel="stylesheet" href="{% static '' %}css/plugins/jquery.classycountdown.min.css">
        <link rel="stylesheet" href="{% static '' %}css/plugins/nouislider.min.css">
        <link rel="stylesheet" href="{% static '' %}css/plugins/sweetalert2.min.css">
        <link rel="stylesheet" href="{% static '' %}css/plugins/select2.min.css">
        <link rel="stylesheet" href="{% static '' %}css/plugins/swiper.min.css">
        <!-- CSS Template -->
        <link rel="stylesheet" href="{% static '' %}css/theme.css">
        <!-- Custom css and js -->
        <link rel="stylesheet" href="{% static '' %}css/custom.css">
        <!-- colors: amber,blue,brown,cyan,default,green,indigo,orange,pink,purple,red,teal,yellow -->
        <link rel="stylesheet" href="{% static '' %}css/colors/default.css" id="colorswitch">
    {% endcompress %}
</head>

<body>

<div class="page-wrapper">

    <!-- Page Header -->
    {% include 'header.html' %}
    <!-- end Page Header -->
    <!-- Page Content -->
    {% block content %}{% endblock %}
    <!-- end Page Content -->

    <!-- Page Footer -->
    {% include 'footer.html' %}
    <!-- end Page Footer -->

</div>

{% compress js %}
    <!-- JS Global Compulsory -->
    <script src="{% static '' %}js/jquery-3.5.1.min.js"></script>
    <script src="{% static '' %}js/plugins/popper.min.js"></script>
    <script src="{% static '' %}bootstrap/js/bootstrap.min.js"></script>
    <!-- JS Implementing Plugins -->
    <script src="{% static '' %}js/plugins/apexcharts.min.js"></script>
    <script src="{% static '' %}js/plugins/jquery.knob.js"></script>
    <script src="{% static '' %}js/plugins/jquery.throttle.js"></script>
    <script src="{% static '' %}js/plugins/jquery.classycountdown.min.js"></script>
    <script src="{% static '' %}js/plugins/jquery.nicescroll.min.js"></script>
    <script src="{% static '' %}js/plugins/nouislider.min.js"></script>
    <script src="{% static '' %}js/plugins/sweetalert2.all.min.js"></script>
    <script src="{% static '' %}js/plugins/select2.full.min.js"></script>
    <script src="{% static '' %}js/plugins/swiper.min.js"></script>
    <script src="{% static '' %}js/plugins/ResizeSensor.min.js"></script>
    <script src="{% static '' %}js/plugins/theia-sticky-sidebar.min.js"></script>
    <script src="{% static '' %}js/plugins/zoomsl.min.js"></script>
    <script src="{% static '' %}js/plugins/wNumb.js"></script>
    <!-- JS Template -->
    <script src="{% static '' %}js/theme.js"></script>
    <!-- Custom.js -->
    <script src="{% static '' %}js/custom.js"></script>
{% endcompress %}
{#    <script>#}
{#        $(document).ready(function () {#}
{#            $('#countdown--offer-slider').ClassyCountdown({#}
{#                theme: "black",#}
{#                end: $.now() + 645600,#}
{#                labels: false,#}
{#            });#}
{#        });#}
{#    </script>#}
<script>
    function makeTimer() {
        let endTime = new Date({{ when.when|date:"U" }} * 1000
    )
        ;
        endTime = (Date.parse(endTime) / 1000);

        let now = new Date();
        now = (Date.parse(now) / 1000);

        let timeLeft = endTime - now;

        let days = Math.floor(timeLeft / 86400);
        let hours = Math.floor((timeLeft - (days * 86400)) / 3600);
        let minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600)) / 60);
        let seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));

        if (hours < "10") {
            hours = "0" + hours;
        }
        if (minutes < "10") {
            minutes = "0" + minutes;
        }
        if (seconds < "10") {
            seconds = "0" + seconds;
        }

        $("#days").html(days + "<span>روز</span>");
        $("#hours").html(hours + "<span>ساعت</span>");
        $("#minutes").html(minutes + "<span>دقیقه</span>");
        $("#seconds").html(seconds + "<span>ثانیه</span>");

    }

    setInterval(function () {
        makeTimer();
    }, 1000);
</script>


</body>

</html>

templates/footer.html
{% load static %}
{% load thumbnail %}
<!-- color switcher -->
{#<div id="colorswitch-option">#}
{#    <button><i class="fas fa-swatchbook"></i></button>#}
{#    <ul>#}
{#        <li data-path="/static/css/colors/amber.css"><span style="background-color: #ffab00;"></span></li>#}
{#        <li data-path="/static/css/colors/blue.css"><span style="background-color: #2962ff;"></span></li>#}
{#        <li data-path="/static/css/colors/brown.css"><span style="background-color: #3e2723;"></span></li>#}
{#        <li data-path="/static/css/colors/cyan.css"><span style="background-color: #00b8d4;"></span></li>#}
{#        <li data-path="/static/css/colors/green.css"><span style="background-color: #00c853;"></span></li>#}
{#        <li data-path="/static/css/colors/indigo.css"><span style="background-color: #304ffe;"></span></li>#}
{#        <li data-path="/static/css/colors/orange.css"><span style="background-color: #ff6d00;"></span></li>#}
{#        <li data-path="/static/css/colors/pink.css"><span style="background-color: #c51162;"></span></li>#}
{#        <li data-path="/static/css/colors/red.css"><span style="background-color: #d50000;"></span></li>#}
{#        <li data-path="/static/css/colors/teal.css"><span style="background-color: #009688;"></span></li>#}
{#        <li data-path="/static/css/colors/purple.css"><span style="background-color: #aa00ff;"></span></li>#}
{#        <li data-path="/static/css/colors/yellow.css"><span style="background-color: #ffd600;"></span></li>#}
{#    </ul>#}
{#</div>#}
<!-- end color switcher -->

<!-- Page Loader -->
{#<div class="page-loader">#}
{#    <div class="page-loader-content">#}
{#        <div class="logo-area">#}
{#            <img src="{% static '' %}images/logo.png" alt="">#}
{#        </div>#}
{#        <span class="loader"></span>#}
{#    </div>#}
{#</div>#}
<!-- end Page Loader -->

<footer class="main-footer">
    <div class="back-to-top">
        <div class="back-btn">
            <i class="far fa-chevron-up icon"></i>
            <span>برگشت به بالا</span>
        </div>
    </div>
    <div class="container">
        <div class="row mb-3">
            <div class="col-md-4 col-sm-6">
                <div class="widget widget-links">
                    <h2 class="widget-title">دسته بندی کالاها</h2>
                    <ul class="widget-list">
                        {% for category in footer_categories %}
                            <li class="widget-list-item">
                                <a href="{{ category.get_absolute_url }}"
                                   class="widget-list-link">{{ category.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="widget widget-links">
                    <h2 class="widget-title">راهنمای خرید از همتا گیم</h2>
                    <ul class="widget-list">
                        <li class="widget-list-item">
                            <a href="#" class="widget-list-link">نحوه ثبت سفارش</a>
                        </li>
                        <li class="widget-list-item">
                            <a href="#" class="widget-list-link">رویه ارسال سفارش</a>
                        </li>
                        <li class="widget-list-item">
                            <a href="#" class="widget-list-link">شیوه‌های پرداخت</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="widget widget-newsletter">
                    <h2 class="widget-title">درباره ما:</h2>
                    <div class="newsletter">
                        <p>{{ site_setting.site_footer_text }}</p>
                    </div>
                </div>
                <div class="widget">
                    <h2 class="widget-title">
                        همتا گیم را در شبکه‌های اجتماعی دنبال کنید:
                    </h2>
                    <div class="social">
                        <ul>
                            <li>
                                <a href="{{ site_setting.site_instagram }}" class="instagram"><i
                                        class="fab fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                {#                <div class="widget">#}
                {#                    <h2 class="widget-title">دانلود اپلیکیشن</h2>#}
                {#                    <div class="d-flex flex-wrap">#}
                {#                        <div class="ml-2 mb-2">#}
                {#                            <a class="btn-market" href="#">#}
                {#                                        <span class="d-flex align-items-center justify-content-between">#}
                {#                                            <span>#}
                {#                                                <span class="btn-market-subtitle">دانلود از</span>#}
                {#                                                <span class="btn-market-title">اپ استور</span>#}
                {#                                            </span>#}
                {#                                            <i class="fab fa-apple"></i>#}
                {#                                        </span>#}
                {#                            </a>#}
                {#                        </div>#}
                {#                        <div class="mb-2">#}
                {#                            <a class="btn-market" href="#">#}
                {#                                        <span class="d-flex align-items-center justify-content-between">#}
                {#                                            <span>#}
                {#                                                <span class="btn-market-subtitle">دانلود از</span>#}
                {#                                                <span class="btn-market-title">گوگل پلی</span>#}
                {#                                            </span>#}
                {#                                            <i class="fab fa-google-play"></i>#}
                {#                                        </span>#}
                {#                            </a>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                </div>#}
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-3">
                <div class="logo-area">
                    <a href="{% url 'store:home_page' %}">
                        {% thumbnail site_setting.site_header_logo "100x100" crop="center" as img %}
                            <img src="{{ img.url }}" alt="{{ site_setting.site_header_logo_alt }}"
                                 title="همتا گیم">
                        {% endthumbnail %}
                    </a>
                </div>
            </div>
            {#            <div class="col-12">#}
            {#                <div class="widget widget-links mb-2">#}
            {#                    <ul class="widget-list d-flex flex-wrap justify-content-center justify-content-md-start">#}
            {#                        <li class="widget-list-item ml-4">#}
            {#                            <a href="#" class="widget-list-link">درباره همتا</a>#}
            {#                        </li>#}
            {#                        <li class="widget-list-item ml-4">#}
            {#                            <a href="#" class="widget-list-link">فروش در همتا</a>#}
            {#                        </li>#}
            {#                        <li class="widget-list-item ml-4">#}
            {#                            <a href="#" class="widget-list-link">فرصت های شغلی</a>#}
            {#                        </li>#}
            {#                        <li class="widget-list-item ml-4">#}
            {#                            <a href="#" class="widget-list-link">تماس با همتا</a>#}
            {#                        </li>#}
            {#                        <li class="widget-list-item ml-4">#}
            {#                            <a href="#" class="widget-list-link">حریم خصوصی</a>#}
            {#                        </li>#}
            {#                    </ul>#}
            {#                </div>#}
            {#            </div>#}
        </div>
        <div class="row text-center">
            <div class="col-12">
                <div class="copy-right" dir="ltr">
                    <p>تمامی حقوق این سایت متعلق به همتا گیم میباشد.</p>
                    <p>طراحی و توسعه: <a href="https://par30code.com" target="_blank">پارسی کد</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
{% load humanize %}
{% load store_tags %}
{% load thumbnail %}
<header class="page-header">
    <div class="top-page-header">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between">
                <div class="contact-list">
                    <ul>
                        <li><i class="fas fa-phone-rotary"></i><a
                                href="tel: {{ site_setting.site_phone }}">{{ site_setting.site_phone }}</a></li>
                        <li><i class="fas fa-envelope"></i><a
                                href="mailto: {{ site_setting.site_email }}">{{ site_setting.site_email }}</a></li>
                    </ul>
                </div>
                <div class="top-header-menu">
                    <ul>
                        <li><a href="{% url 'blog:blog_home' %}"><i class="fa fa-gamepad text-info"></i> مجله</a></li>
                        {% if request.user.is_superuser %}
                            <li><a href="/admin" target="_blank">پنل ادمین</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="bottom-page-header">
            <div class="d-flex align-items-center">
                <div class="site-logo">
                    <a href="{% url 'store:home_page' %}">
                        {% thumbnail site_setting.site_header_logo "50x50" crop="center" as img %}
                            <img src="{{ img.url }}" alt="{{ site_setting.site_header_logo_alt }}">
                        {% endthumbnail %}
                    </a>
                </div>
                <div class="search-box">
                    <form action="{% url 'store:search' %}" method="get">
                        <input type="search" id="q" name="q" placeholder="نام محصول یا برند را جستجو کنید...">
                        <i class="far fa-search"></i>
                    </form>
                </div>
            </div>
            <div class="user-items">
                <div class="user-item">
                    <a href="{% url 'accounts:favourite' %}">
                        <i class="fal fa-heart"></i>
                        <span class="bag-items-number">
                            {% if request.user.is_authenticated %}
                                {{ request.user.favourites_user.all.count }}
                            {% else %}
                                0
                            {% endif %}
                        </span>
                    </a>
                </div>
                <div class="user-item cart-list">
                    <a href="{% url 'cart:cart_detail' %}">
                        <i class="fal fa-shopping-basket"></i>


                        {% with total_qty=cart|length %}
                            {% if total_qty > 0 %}
                                <span class="bag-items-number">{{ total_qty }}</span>
                            {% else %}
                                <span class="bag-items-number">0</span>
                            {% endif %}
                        {% endwith %}


                    </a>
                    <ul>
                        <li class="cart-items">
                            {% if cart %}
                                <ul class="do-nice-scroll">
                                    {% for item in cart %}
                                        <li class="cart-item">
                                            <span class="d-flex align-items-center mb-2">
                                                <a href="{{ item.variant.product.get_absolute_url }}">
                                                    <img src="{{ item.variant.product.image.url }}"
                                                         alt="{{ item.variant.product.image_alt }}">
                                                </a>
                                                <span>
                                                    <a href="{{ item.variant.product.get_absolute_url }}">
                                                        <span class="title-item">
                                                            {{ item.variant.product.title }}
                                                        </span>
                                                    </a>
                                                    {% if item.variant.console_variant %}
                                                        <span class="d-flex align-items-center">
                                                        گارانتی:
                                                        <span>{{ item.variant.console_variant.title }}</span>
                                                    </span>
                                                    {% else %}
                                                        <span class="d-flex align-items-center">
                                                        گارانتی:
                                                        <span>ندارد</span>
                                                    </span>
                                                    {% endif %}
                                                    {% if item.variant.controller_variant %}
                                                        <span class="d-flex align-items-center">
                                                        گارانتی دسته:
                                                        <span>{{ item.variant.controller_variant.title }}</span>
                                                    </span>
                                                    {% else %}
                                                        <span class="d-flex align-items-center">
                                                        گارانتی دسته:
                                                        <span>ندارد</span>
                                                    </span>
                                                    {% endif %}
                                                    <span class="d-flex align-items-center">
                                                        تعداد:
                                                        <span>{{ item.quantity }}</span>
                                                    </span>
                                                <span class="d-flex align-items-center">
                                                        قیمت:
                                                        <span class="price">{{ item.variant.total_price|intcomma:False }} تومان</span>
                                                    </span>
                                                <span class="d-flex align-items-center">
                                                        قیمت کل:
                                                        <span class="price">{% widthratio item.variant.total_price 1 item.quantity as total %}</span>
                                                        <span class="price">{{ total|intcomma:False }} تومان</span>
                                                    </span>
                                            </span>

                                    <a href="{% url 'cart:remove_from_cart' item.variant.id %}"
                                       class="btn btn-outline-info">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </li>
                        <li class="cart-footer d-flex align-items-center justify-content-between">

                            {% if cart %}
                                <span class="d-flex flex-column">
                                        <span>مبلغ کل:</span>
                                        <span class="total">{{ cart.get_total_price|intcomma:False }} تومان</span>
                                    </span>
                                <span class="d-block text-center px-2">
                                        <a href="{% url 'cart:cart_detail' %}" class="btn-cart">
                                            مشاهده سبد خرید
                                        </a>
                                    </span>
                            {% else %}
                                <span class="badge badge-info text-center">
                                        سبد خرید شما خالی است.
                                    </span>
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <div class="user-item account">
                    {% if request.user.is_authenticated %}
                        <a href="#">
                            {{ request.user.username }}
                            <i class="fad fa-chevron-down text-sm mr-1"></i>
                        </a>
                        <ul class="dropdown--wrapper">
                            <li class="header-profile-dropdown-account-container">
                                <a href="{% url 'accounts:dashboard' %}" class="d-block">
                                        <span class="header-profile-dropdown-user">
                                            <span class="header-profile-dropdown-user-img">
                                                <img src="



                                                        {% if request.user.image %}{{ request.user.image.url }}{% else %}{% static '' %}images/avatar/avatar.png{% endif %}">
                                            </span>
                                            <span class="header-profile-dropdown-user-info">
                                                <p class="header-profile-dropdown-user-name">
                                                    {{ request.user.username }}
                                                </p>
                                                <span class="header-profile-dropdown-user-profile-link">مشاهده حساب
                                                    کاربری</span>
                                            </span>
                                        </span>
                                </a>
                            </li>
                            <hr>
                            <li>
                                <a href="{% url 'accounts:dashboard' %}">
                                    پروفایل
                                </a>
                            </li>
                            <li class="text-success">
                                <a href="{% url 'accounts:logout_page' %}">
                                    خروج از حساب کاربری
                                </a>
                            </li>
                        </ul>
                    {% else %}
                        <a href="{% url 'accounts:login_page' %}" class="btn-auth">
                            <i class="fal fa-user-circle"></i>
                            ورود و عضویت
                        </a>
                        <ul class="dropdown--wrapper">
                            <li>
                                <a href="{% url 'accounts:login_page' %}" class="dropdown--btn-primary">وارد شوید</a>
                            </li>
                            <li>
                                <span>کاربر جدید هستید؟</span>
                                <a href="{% url 'accounts:register_page' %}" class="border-bottom-dt">ثبت نام</a>
                            </li>
                            <hr>
                        </ul>
                    {% endif %}

                </div>
            </div>
        </div>
        {% store_navbar_desktop %}
    </div>
    {% include 'messages.html' %}
    {% if request.user.is_authenticated and not request.user.is_verify %}
        <div class="alert alert-danger" role="alert">
            کاریر گرامی، لطفا شماره همراه خود را <a href="{% url 'accounts:verify_register' %}">تایید</a> کنید.
        </div>
    {% endif %}
</header>
<!-- header responsive -->
{% store_navbar_responsive %}
{% include 'messages.html' %}
{% if request.user.is_authenticated and not request.user.is_verify %}
    <div class="alert alert-danger" role="alert">
        کاریر گرامی، لطفا شماره همراه خود را <a href="{% url 'accounts:verify_register' %}">تایید</a> کنید.
    </div>
{% endif %}
<!-- end header responsive -->